# LS solver

*Advanced Econometrics 2016-2017. Case 1, least squares (LS) implementation.*

## Problem
Ordinary Least Squares (OLS) is a solution for a system of linear equations by minimizing the sum of squared differences between the observed values ($y$) and the corresponding modelled values ($\hat y = X \hat\beta$).

A system of equations is given by
$$ y_i = \beta_1 + \beta_2 X_{i2}  + \beta_3 X_{i3}  + ... + \beta_K X_{iK} + \mu_i,  \quad i=1,...,N$$

or in matrix notation
$$ y = X \beta + \mu$$

with $y, \mu \in \mathbb{R}^{N\times1}$, $X \in \mathbb{R}^{N\times K}$ and $\beta \in \mathbb{R}^{K\times 1}$.

The OLS solves
$$\operatorname{\,min} \, \big\|y - X \hat\beta \big\|^2$$
that with some algebra leads to the [normal equations](https://en.wikipedia.org/wiki/Normal_equations) 
$$ X' X\beta = X'y$$ 

## Solution

### Normal equations

In case of a [rank][1] complete matrix $X$ the normal equations can be solved by inverting the ([Gram](https://en.wikipedia.org/wiki/Gramian_matrix)) matrix $X'X$ such that $\hat\beta = (X'X)^{-1}Xy$.

As X'X is a symmetric, positive definite matrix it's computationally more efficient to use the cholesky decomposition of $X'X = LL'$ with $L$ a lower triangular matrix. This gives $LL'\hat\beta = X'y$. First solve $Lz = X'y$ for $z$ by [forward substitution](https://en.wikipedia.org/wiki/Forward_substitution) and then $L'\hat\beta = z$ for $\beta$ by backward substitution.

However, solving the normal equations is numerically unstable, i.e. it is very sensitive to small pertubations in $X$. The [condition number](https://en.wikipedia.org/wiki/Condition_number) $\kappa$ of the system is worsened: $\kappa(X'X) = [\kappa(X)]^2$. We show the impact further below.

[1]: https://en.wikipedia.org/wiki/Rank_(linear_algebra)

We first simulate some parameters and data using the same notation as in the slides.

In [1]:
K = 5   # number of parameters
N = 100 # number of observations

# Create actual parameters and observations
β = randn(K)
X = randn(N, K)
X[:,1] = ones(N) # intercept
σ = 0.1
μ = randn(N) * σ # ~ N(0,1)
y = X * β + μ;

In [4]:
#define function
OLS_normal(y, X) = inv(X'X) * X'y

# test and print result side by side for quick sanity check
β̂_normal = OLS_normal(y, X)
hcat(β̂_normal, β)

5×2 Array{Float64,2}:
  2.19354    2.1908  
 -0.763111  -0.758047
  1.02621    1.03849 
  1.29059    1.27825 
  1.59663    1.59965 

In [5]:
function OLS_chol(y, X)
    X′X_chol = cholfact(X'X)
    X′X_chol\(X'*y)
end

# test and print result side by side for quick sanity check
β̂_chol = OLS_chol(y, X)
hcat(β̂_chol, β)

5×2 Array{Float64,2}:
  2.19354    2.1908  
 -0.763111  -0.758047
  1.02621    1.03849 
  1.29059    1.27825 
  1.59663    1.59965 

### QR Factorization
We decompose $X$ to its orthogonal [QR decomposition](https://en.wikipedia.org/wiki/QR_decomposition):
$$X = Q\begin{bmatrix}
R \\
0
\end{bmatrix} $$
with $Q\in\mathbb{R}^{N\times N} $ an [orthogonal matrix](https://en.wikipedia.org/wiki/Orthogonal_matrix) and $R\in\mathbb{R}^{k\times k}$ an upper triangular matrix (with positive diagonal elements).
The solution is then given by
$$R \hat\beta =\left(Q' \mathbf y \right)_K$$

This is the default method in Julia for solving OLS (for non-square matrix $X$) with `β̂ = X\y`

In [6]:
function OLS_qr(y, X)
    X_qr = qrfact(X)
    X_qr \ y
end


OLS_qr (generic function with 1 method)

In [7]:
β̂_qr = OLS_qr(y, X)
hcat(β̂_qr, β)

5×2 Array{Float64,2}:
  2.19354    2.1908  
 -0.763111  -0.758047
  1.02621    1.03849 
  1.29059    1.27825 
  1.59663    1.59965 

### SVD
Another orthogonal decomposition uses the [singular value decomposition](https://en.wikipedia.org/wiki/Singular_value_decomposition) (SVD) of $X$:
$$X = U \Sigma V'$$
with $U \in\mathbb{R}^{N\times N}$ and $V \in\mathbb{R}^{K\times K}$ both an orthogonal matrix, and $\Sigma\in\mathbb{R}^{N\times K}$ a diagonal matrix. SVD can transform any matrix into a diagonal matrix with the right choice of orthogonal coordinate systems for its domain and range. This even works for rank deficient matrices and is numerically stable! In such an ill-conditioned system, SVD will return the solution $\hat\beta$ that has the smallest norm.




In [8]:
function OLS_svd(y, X)
    X_svd = svdfact(X)
    X_svd \ y
end

OLS_svd (generic function with 1 method)

In [9]:
β̂_svd = OLS_svd(y, X)
hcat(β̂_svd, β)

5×2 Array{Float64,2}:
  2.19354    2.1908  
 -0.763111  -0.758047
  1.02621    1.03849 
  1.29059    1.27825 
  1.59663    1.59965 

## Numerical Stability
We now test numerical stability (example 3.5 in [1]) with 
$$X^s = \begin{bmatrix}
1 & 1\\
1 & 1+\epsilon
\end{bmatrix}, 
y^s = \begin{bmatrix}
2 \\
2 
\end{bmatrix}$$
This gives the solution $\hat\beta=\begin{bmatrix}2 & 0\end{bmatrix}'$ .

This system is ill-conditioned because a slight perturbation in $$y^s_e = \begin{bmatrix}
2 \\
2 + \epsilon
\end{bmatrix}$$
gives the compeltely different solution $\hat\beta=\begin{bmatrix}1 & 1\end{bmatrix}'$

We show that methods using the normal equations do not find the second solution.

[1]: Numerically Efficient Methods for Solving Least Squares Problems, Do Q Lee.

In [10]:
ϵ = 1e-7
Xˢ = [1 1;1 1+ϵ]
yˢ = [2; 2]
OLS_normal(yˢ, Xˢ)

2-element Array{Float64,1}:
 2.0
 0.0

In [11]:
yˢₑ = [2; 2+ϵ]
@show OLS_normal(yˢₑ, Xˢ)
@show OLS_chol(  yˢₑ, Xˢ);

OLS_normal(yˢₑ,Xˢ) = [0.75,1.125]
OLS_chol(yˢₑ,Xˢ) = [0.727273,1.27273]


In [12]:
@show OLS_qr( yˢₑ, Xˢ)
@show OLS_svd(yˢₑ, Xˢ);

OLS_qr(yˢₑ,Xˢ) = [1.0,1.0]
OLS_svd(yˢₑ,Xˢ) = [1.0,1.0]


# Case 

In [13]:
type OLSresult
    coefs
    se
    tstats
    p
    res
end

In [14]:
using Distributions

In [ ]:
1+1

In [ ]:
TDist()

In [ ]:
function LS(y, X; correction= :none)
    if correcton = :none
        β̂ = OLS_svd(y, X)
        μ̂ = X*β̂ - y
        

In [ ]:
u

### Advanced methods
Several advanced methods exist such as [bayesian OLS](https://en.wikipedia.org/wiki/Bayesian_linear_regression) (with possible priors), sparse OLS solvers, and iterative solvers. Several other methods for OLS exist , 

In [1]:
using IterativeSolvers

In [5]:
OLS_lsmr(y, X) = lsmr(X, y)

OLS_lsmr (generic function with 1 method)

In [6]:
β̂_lsmr = OLS_lsmr(y, X)
hcat(β̂_lsmr, β)

5×2 Array{Float64,2}:
 -0.673437  -0.671959
  0.998477   0.993547
  0.566924   0.567868
 -0.930122  -0.928808
  0.367578   0.34622 

(also exists [James-Stein estimator](https://en.wikipedia.org/wiki/James%E2%80%93Stein_estimator))